### ISSUE TITLE
Discuss about changing the same attribute multiple times

### ISSUE THREAD

**Issue by lonre** [dylanahsmith/ar_transaction_changes#12]
If we do something like this:

```ruby
user = User.create!(name: 'a')

User.transaction do
  user.update_attribute(:name, 'b')
  user.update_attribute(:name, 'a')
end
```

should we store `name` as changed attributes?

**Comment by dylanahsmith** [comment]
The behaviour should probably be consistent with active record's `changed_attributes`, which seems to omit changes to attributes that were changed back.  So it looks like this is a bug.

**Comment by chriscz** [comment]
By the looks of the changes in the merged PR, this can be closed.
