### ISSUE TITLE
side effect write_attribute private

### ISSUE THREAD

**Issue by eproulx-petalmd** [dylanahsmith/ar_transaction_changes#14]
Hi,

I can't use `write_attribute` anymore since it's a now private method. Could you make it public like in the framework ? https://apidock.com/rails/ActiveRecord/AttributeMethods/write_attribute

Thanks

**Comment by dylanahsmith** [comment]
Fixed by https://github.com/dylanahsmith/ar_transaction_changes/pull/15

**Comment by ericproulx** [comment]
Are you gonna release a new version soon ?

**Comment by dylanahsmith** [comment]
Sure.  I've pushed a release
