### ISSUE TITLE
Multiple instances of the same object in a transaction

### ISSUE THREAD

**Issue by naveedkakal** [dylanahsmith/ar_transaction_changes#27]
Hi, thanks for the effort on this library!

I found a situation that is of similar nature to the changes being cleared on each save, and wanted to see if you have any ideas or input on this situation.

```ruby
# Rails 4.2
ActiveRecord::Base.transaction do
  user = User.find(1)
  user.update(first_name: "William")

  # Same user_id, but different object
  same_user = User.find(1)
  same_user.update(last_name: "Riker")
end
```

In this situation, only one `after_commit` callback will be fired, and there's no ability to detect the `last_name` change in the `after_commit` callback.

I believe this is because before the commit callbacks are fired, ActiveRecord `uniqs` the collection of committed objects.

This seems like a really big gotcha in using `after_commit` callbacks with the intention of tracking changes, and I was wondering if you had any suggestions on tackling this.

For my own use case, I was considering doing something like defining an `after_save` callback just to collect changes in some sort of model/id/hash tree in a `Thread.current` variable, and then in `after_commit` processing the collected changes.

I'm also open to the idea that I'm just doing something the framework doesn't support and perhaps needing to find a different strategy overall to publish these changes to external systems (RabbitMQ in my case).  

A related issue that seems to have gone stale -
https://github.com/rails/rails/issues/27342

**Comment by dylanahsmith** [comment]
That seems like a huge gotcha in active record itself.  I would have expected it to avoid calling `after_commit` on the same object twice, but not to do this across objects.  That seems like an upstream problem I wouldn't want to workaround.

I checked to see if that is still the current behaviour of rails and it looks like rails 6.0 change the duplicate removal to [`records.uniq(&:object_id)`](https://github.com/rails/rails/blob/49baf092439fc74fc3377b12e3334c3dd9d0752f/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L139), so it seems like that rails issue might have actually have been fixed.

**Comment by naveedkakal** [comment]
Thanks for your input!

I've come across a few different rails issues/PRs that talk about this one.  This was never an issue with this library and so I'm going to close the issue.

Am trying to navigate how to address this in my Rails 4.2 app - I can monkey patch the `commit_records` method to use `uniq(&:object_id)` - but I'm not really sure what the extent of impact will be, and if that is enough on its own (or what it breaks by adding).

A 'safer' way for my specific case, may be to use the `Thread.current` type of change tracking in after save.

Leaving some links here to references I found in case it helps in the the future for anyone digging in to similar issue:

https://github.com/rails/rails/pull/36190 - The PR which adds `uniq(&:object_id)` (I wasn't able to fully understand the purpose / intent of other changes)

https://github.com/rails/rails/pull/38990 - Followup PR which uses `__id__` instead of `object_id` in case the model defines it's own `object_id`

https://github.com/rails/rails/issues/27342 - Similar issue to the above reported, with some decent links to the fixes so far, and why reloading is problematic

https://github.com/rails/rails/issues/39400 - Similar issue reported again, with some notes about why we de-dup (updates via associations could result in more after_commits than expected)

**Comment by naveedkakal** [comment]
> I checked to see if that is still the current behaviour of rails and it looks like rails 6.0 change the duplicate removal to records.uniq(&:object_id), so it seems like that rails issue might have actually have been fixed.

From more research on this - It seems the PR that added the `object_id` to `uniq` also added some code to explicitly maintain the existing behavior of only running once per model/id - I think there is fear of it being a breaking change if after_commit callbacks which were previously not run to start firing.  Interesting situation!
