### ISSUE TITLE
previous_changes vs transaction_changed_attributes

### ISSUE THREAD

**Issue by chamnap** [dylanahsmith/ar_transaction_changes#4]
It's just my curiousity. There is a method provided by AR `#previous_changes`. What are the differences between `#previous_changes` by AR and `#transaction_changed_attributes` provided by this gem?

http://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-previous_changes

**Comment by arthurnn** [comment]
I was questioning my self too about this.. @byroot, pointed out that the Rails method will lose the changes if you call `save` twice.. I didnt test that, but seems to be the case..
@dylanahsmith can you confirm that, and if thats the only reason add it to the README of the project?
